"""
Cross-language golden byte verification (Python side).

The golden frames under <repo>/test/protocol-golden are generated by the
authoritative Java implementation (NovaChat/common, GoldenFileGenerator).
For every sample this suite:

1. decodes the .bin frame with the Endstone protocol classes,
2. asserts every decoded field matches the .json descriptor,
3. re-encodes and asserts byte-for-byte equality with the .bin
   (skipped for legacyWire samples and Python knownDrift samples).

Historical Python drift, now fixed (regression-pinned in
test_fixed_drift_is_byte_exact):

- ChatMessagePacket used to drop the placeholders map (decode discarded
  contents, encode always wrote varint 0); it now round-trips the map.
- ConfigSyncPacket.encode used to normalize an empty config_json string to
  "{}" ("or" treated the empty string as falsy); like Java it now only maps
  None to "{}" and preserves the empty string.
"""

from __future__ import annotations

import json
import uuid
from pathlib import Path

import pytest

from novachat_endstone.protocol.buffer import PacketBuffer
from novachat_endstone.protocol.varint import VarInt
from novachat_endstone.protocol.packet import (
    AdminActionPacket,
    AdminActionResponsePacket,
    ChannelActionPacket,
    ChannelActionResponsePacket,
    ChatMessagePacket,
    ConfigSyncPacket,
    HandshakePacket,
    HandshakeResponsePacket,
    ItemDisplayPacket,
    KeepAlivePacket,
    MentionPacket,
    Packet,
    PrivateMessagePacket,
    TitleMessagePacket,
    UnknownPacket,
    decode_packet,
)


def _repo_root() -> Path:
    current = Path(__file__).resolve().parent
    for candidate in (current, *current.parents):
        if (candidate / "settings.gradle").exists() or (candidate / ".git").exists():
            return candidate
    raise RuntimeError(f"Could not locate repository root above {current}")


GOLDEN_DIR = _repo_root() / "test" / "protocol-golden"


def _load_samples() -> list[dict]:
    manifest_path = GOLDEN_DIR / "manifest.json"
    if not manifest_path.exists():
        raise RuntimeError(
            f"Golden manifest not found: {manifest_path} "
            "(run the Java GoldenFileGenerator first)"
        )
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    samples = []
    for entry in manifest["samples"]:
        descriptor = json.loads(
            (GOLDEN_DIR / f"{entry['name']}.json").read_text(encoding="utf-8")
        )
        samples.append(descriptor)
    return samples


SAMPLES = _load_samples()
# Samples whose Python re-encode used to drift from the golden bytes; the
# drift is fixed and must never come back.
FIXED_DRIFT_SAMPLES = [
    s for s in SAMPLES
    if s["name"] in ("chat_message_full", "config_sync_empty_string")
]

# Field assertion tables: JSON descriptor key -> Python attribute name.
# UUID-valued JSON fields are compared as uuid.UUID.
_STR_UUID_FIELDS = {
    "senderId", "playerId", "mentionerId", "mentionedId", "targetId",
}
_FIELD_MAPS: dict[type, dict[str, str]] = {
    HandshakePacket: {
        "protocolVersion": "protocol_version",
        "clientId": "client_id",
        "passwordHash": "password_hash",
        "platform": "platform",
        "serverVersion": "server_version",
    },
    HandshakeResponsePacket: {
        "success": "success",
        "errorCode": "error_code",
        "message": "message",
    },
    ChatMessagePacket: {
        "senderId": "sender_id",
        "senderName": "sender_name",
        "clientId": "client_id",
        "channelId": "channel_id",
        "content": "content",
        "placeholders": "placeholders",
    },
    ChannelActionPacket: {
        "action": "action",
        "channelId": "channel_id",
        "password": "password",
        "extra": "extra",
    },
    ChannelActionResponsePacket: {
        "success": "success",
        "action": "action",
        "channelId": "channel_id",
        "errorCode": "error_code",
        "message": "message",
        "extra": "extra",
    },
    ConfigSyncPacket: {
        "configJson": "config_json",
        "timestamp": "timestamp",
    },
    KeepAlivePacket: {
        "timestamp": "timestamp",
    },
    TitleMessagePacket: {
        "channelId": "channel_id",
        "title": "title",
        "subtitle": "subtitle",
        "fadeIn": "fade_in",
        "stay": "stay",
        "fadeOut": "fade_out",
        "senderId": "sender_id",
    },
    AdminActionPacket: {
        "action": "action",
        "playerId": "player_id",
        "passwordHash": "password_hash",
        "target": "target",
        "extra": "extra",
    },
    AdminActionResponsePacket: {
        "action": "action",
        "success": "success",
        "errorCode": "error_code",
        "message": "message",
    },
    ItemDisplayPacket: {
        "senderId": "sender_id",
        "senderName": "sender_name",
        "channelId": "channel_id",
        "itemJson": "item_json",
        "timestamp": "timestamp",
    },
    MentionPacket: {
        "mentionerId": "mentioner_id",
        "mentionerName": "mentioner_name",
        "mentionedId": "mentioned_id",
        "channelId": "channel_id",
        "messagePreview": "message_preview",
        "timestamp": "timestamp",
    },
    PrivateMessagePacket: {
        "senderId": "sender_id",
        "senderName": "sender_name",
        "senderClientId": "sender_client_id",
        "targetName": "target_name",
        "targetId": "target_id",
        "content": "content",
        "timestamp": "timestamp",
    },
}


def _decode_frame(frame: bytes) -> tuple[int, uuid.UUID, Packet, PacketBuffer]:
    """Parse Length(VarInt) | PacketID | RequestID | Payload."""
    length, consumed = VarInt.decode(frame)
    body = frame[consumed:]
    assert length == len(body), "VarInt length prefix must equal body size"
    buffer = PacketBuffer(body)
    packet_id = buffer.read_byte()
    request_id = buffer.read_uuid()
    packet = decode_packet(packet_id, buffer)
    return packet_id, request_id, packet, buffer


def _encode_frame(packet: Packet, request_id: uuid.UUID) -> bytes:
    buffer = PacketBuffer()
    buffer.write_byte(packet.packet_id)
    buffer.write_uuid(request_id)
    packet.encode(buffer)
    body = buffer.get_bytes()
    return VarInt.encode(len(body)) + body


@pytest.mark.parametrize("descriptor", SAMPLES, ids=lambda s: s["name"])
def test_golden_sample(descriptor: dict) -> None:
    name = descriptor["name"]
    frame = (GOLDEN_DIR / f"{name}.bin").read_bytes()

    assert frame.hex() == descriptor["frameHex"], f"{name}: frameHex matches .bin"

    packet_id, request_id, packet, buffer = _decode_frame(frame)

    if isinstance(packet, UnknownPacket):
        pytest.skip(
            f"Python has no packet class for packetId 0x{descriptor['packetId']:02X} "
            f"(sample {name})"
        )

    assert packet_id == descriptor["packetId"], f"{name}: packet id"
    assert request_id == uuid.UUID(descriptor["requestId"]), f"{name}: request id"
    assert buffer.remaining() == 0, f"{name}: payload fully consumed"

    field_map = _FIELD_MAPS[type(packet)]
    for json_key, attr in field_map.items():
        expected = descriptor["fields"][json_key]
        actual = getattr(packet, attr)
        if json_key in _STR_UUID_FIELDS:
            expected = uuid.UUID(expected)
        assert actual == expected, f"{name}: field {json_key}"

    if not descriptor["reencodeExact"] or "python" in descriptor.get("knownDrift", {}):
        return  # legacy wire form or documented Python drift: decode-only.

    reencoded = _encode_frame(packet, request_id)
    assert reencoded.hex() == frame.hex(), (
        f"{name}: re-encoded frame is byte-identical to the golden frame"
    )


@pytest.mark.parametrize("descriptor", FIXED_DRIFT_SAMPLES, ids=lambda s: s["name"])
def test_fixed_drift_is_byte_exact(descriptor: dict) -> None:
    """Regression pin for the fixed Python drift.

    ChatMessage placeholders were dropped and ConfigSync normalized an empty
    config_json to "{}"; these samples must now re-encode byte-identical to
    the golden frame.
    """
    name = descriptor["name"]
    frame = (GOLDEN_DIR / f"{name}.bin").read_bytes()

    _, request_id, packet, _ = _decode_frame(frame)
    assert not isinstance(packet, UnknownPacket)

    reencoded = _encode_frame(packet, request_id)
    assert reencoded.hex() == frame.hex(), (
        f"{name}: fixed drift must stay fixed (re-encode is byte-identical)"
    )
