// Cross-language golden byte verification (C++ side).
//
// The golden frames under <repo>/test/protocol-golden are generated by the
// authoritative Java implementation (NovaChat/common, GoldenFileGenerator).
// For every sample this runner:
//   1. decodes the .bin frame with the LeviLamina protocol classes,
//   2. re-encodes and asserts byte-for-byte equality with the .bin
//      (legacy wire forms are decode-only),
//   3. asserts hardcoded field expectations for one representative sample
//      per packet type (semantic spot checks - a swapped-field bug would
//      survive a pure re-encode comparison).
//
// Historical C++ drift, now fixed (these samples are byte-exact again):
//   - chat_message_full: ChatMessagePacket used to drop the placeholders map
//     (read discarded, write always emitted varint 0); it now round-trips it.
//   - config_sync_empty_string: ConfigSyncPacket::write used to normalize an
//     empty configJson to "{}"; like Java it now preserves the empty string.
//
// Golden dir resolution: NOVALINK_REPO_ROOT env var, else walk up from the
// current working directory looking for settings.gradle / .git.
//
// Build & run:
//   xmake f --sdk=n -m debug
//   xmake build novachat-levilamina-golden-tests
//   xmake run novachat-levilamina-golden-tests
//
// Exits 0 on success, non-zero on the first failure.

#include "../src/protocol/PacketBuffer.h"
#include "../src/protocol/VarInt.h"
#include "../src/protocol/PacketIds.h"
#include "../src/protocol/Packet.h"

#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <memory>
#include <set>
#include <string>
#include <vector>

using namespace novachat::protocol;
namespace fs = std::filesystem;

static int gPassed = 0;
static int gFailed = 0;

#define CHECK_MSG(cond, name, what) do { \
    if (cond) { ++gPassed; } \
    else { ++gFailed; std::printf("FAIL: [%s] %s (%s:%d)\n", (name), (what), __FILE__, __LINE__); } \
} while (0)

// ==================== golden dir resolution ====================

static bool isRepoRoot(const fs::path& p) {
    std::error_code ec;
    return fs::exists(p / "settings.gradle", ec) || fs::exists(p / ".git", ec);
}

static fs::path findGoldenDir() {
    if (const char* env = std::getenv("NOVALINK_REPO_ROOT")) {
        fs::path root(env);
        if (fs::exists(root)) {
            return root / "test" / "protocol-golden";
        }
        std::printf("WARN: NOVALINK_REPO_ROOT does not exist: %s\n", env);
    }
    std::error_code ec;
    fs::path current = fs::current_path(ec);
    while (!current.empty()) {
        if (isRepoRoot(current)) {
            return current / "test" / "protocol-golden";
        }
        fs::path parent = current.parent_path();
        if (parent == current) {
            break;
        }
        current = parent;
    }
    return {};
}

static std::vector<uint8_t> readFile(const fs::path& path) {
    std::ifstream in(path, std::ios::binary);
    return std::vector<uint8_t>((std::istreambuf_iterator<char>(in)),
                                std::istreambuf_iterator<char>());
}

// ==================== packet factory (mirrors NovaProtocol.createRegistry) ====================

static std::unique_ptr<Packet> createPacket(uint8_t packetId) {
    switch (packetId) {
        case PacketIds::HANDSHAKE:               return std::make_unique<HandshakePacket>();
        case PacketIds::HANDSHAKE_RESPONSE:      return std::make_unique<HandshakeResponsePacket>();
        case PacketIds::CHAT_MESSAGE:            return std::make_unique<ChatMessagePacket>();
        case PacketIds::CHANNEL_ACTION:          return std::make_unique<ChannelActionPacket>();
        case PacketIds::CHANNEL_ACTION_RESPONSE: return std::make_unique<ChannelActionResponsePacket>();
        case PacketIds::CONFIG_SYNC:             return std::make_unique<ConfigSyncPacket>();
        case PacketIds::KEEP_ALIVE:              return std::make_unique<KeepAlivePacket>();
        case PacketIds::TITLE:                   return std::make_unique<TitlePacket>();
        case PacketIds::ADMIN_ACTION:            return std::make_unique<AdminActionPacket>();
        case PacketIds::ADMIN_ACTION_RESPONSE:   return std::make_unique<AdminActionResponsePacket>();
        case PacketIds::ITEM_DISPLAY:            return std::make_unique<ItemDisplayPacket>();
        case PacketIds::MENTION:                 return std::make_unique<MentionPacket>();
        case PacketIds::PRIVATE_MESSAGE:         return std::make_unique<PrivateMessagePacket>();
        default:                                 return nullptr;
    }
}

static std::vector<uint8_t> encodeFrame(const Packet& packet) {
    PacketBuffer body;
    body.writeByte(packet.getPacketId());
    body.writeUUID(packet.getRequestId());
    packet.write(body);
    PacketBuffer out;
    out.writeVarInt(static_cast<int32_t>(body.size()));
    out.writeBytes(body.getData().data(), body.size());
    return out.getData();
}

// ==================== hardcoded field expectations (spot checks) ====================

static const UUID UUID_A{0x1122334455667788ULL, 0x99aabbccddeeff00ULL}; // 11223344-5566-7788-99aa-bbccddeeff00
static const UUID UUID_B{0xfedcba9876543210ULL, 0xfedcba9876543210ULL}; // fedcba98-7654-3210-fedc-ba9876543210
static const UUID UUID_NIL{0ULL, 0ULL};

static UUID rid(uint64_t n) { return UUID{0ULL, n}; }

static void checkFields(const std::string& name, const Packet& packet) {
    if (name == "handshake_v2_full") {
        const auto& p = static_cast<const HandshakePacket&>(packet);
        CHECK_MSG(packet.getRequestId() == rid(0x2a), name.c_str(), "requestId");
        CHECK_MSG(p.getProtocolVersion() == 2, name.c_str(), "protocolVersion");
        CHECK_MSG(p.getClientId() == "bedrock-lobby-01", name.c_str(), "clientId");
        CHECK_MSG(p.getPasswordHash() ==
                  "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
                  name.c_str(), "passwordHash");
        CHECK_MSG(p.getPlatform() == PlatformType::POCKETMINE, name.c_str(), "platform");
        CHECK_MSG(p.getServerVersion() == "1.21.44", name.c_str(), "serverVersion");
    } else if (name == "handshake_v1_no_serverversion") {
        const auto& p = static_cast<const HandshakePacket&>(packet);
        CHECK_MSG(p.getProtocolVersion() == 1, name.c_str(), "protocolVersion");
        CHECK_MSG(p.getClientId() == "老服-①区", name.c_str(), "clientId (Chinese UTF-8)");
        CHECK_MSG(p.getPlatform() == PlatformType::LEVILAMINA, name.c_str(), "platform");
        CHECK_MSG(p.getServerVersion().empty(), name.c_str(), "serverVersion empty (v1 legacy wire)");
    } else if (name == "handshake_response_failure") {
        const auto& p = static_cast<const HandshakeResponsePacket&>(packet);
        CHECK_MSG(!p.isSuccess(), name.c_str(), "success");
        CHECK_MSG(p.getErrorCode() == "NC-420", name.c_str(), "errorCode");
        CHECK_MSG(p.getMessage() == "Protocol version mismatch: v1 rejected", name.c_str(), "message");
    } else if (name == "chat_message_full") {
        const auto& p = static_cast<const ChatMessagePacket&>(packet);
        CHECK_MSG(p.getSenderId() == UUID_A, name.c_str(), "senderId");
        CHECK_MSG(p.getSenderName() == "Steve", name.c_str(), "senderName");
        CHECK_MSG(p.getClientId() == "survival-01", name.c_str(), "clientId");
        CHECK_MSG(p.getChannelId() == "global", name.c_str(), "channelId");
        CHECK_MSG(p.getContent() == "Hello, 世界! 🎉", name.c_str(), "content (UTF-8 + emoji)");
        CHECK_MSG(p.getPlaceholders().size() == 1, name.c_str(), "placeholders size");
        CHECK_MSG(!p.getPlaceholders().empty()
                      && p.getPlaceholders()[0].first == "player_level"
                      && p.getPlaceholders()[0].second == "42",
                  name.c_str(), "placeholders[player_level]");
    } else if (name == "chat_message_legacy_no_placeholders") {
        const auto& p = static_cast<const ChatMessagePacket&>(packet);
        CHECK_MSG(p.getChannelId() == "lobby", name.c_str(), "channelId");
        CHECK_MSG(p.getPlaceholders().empty(), name.c_str(), "placeholders empty (legacy wire)");
    } else if (name == "channel_action_create_extra") {
        const auto& p = static_cast<const ChannelActionPacket&>(packet);
        CHECK_MSG(p.getAction() == ChannelAction::CREATE, name.c_str(), "action");
        CHECK_MSG(p.getChannelId() == "vip-频道", name.c_str(), "channelId");
        CHECK_MSG(p.getPassword() == "s3cret!", name.c_str(), "password");
        CHECK_MSG(p.getExtra().size() == 1, name.c_str(), "extra size");
        auto it = p.getExtra().find("displayName");
        CHECK_MSG(it != p.getExtra().end() && it->second == "VIP 频道 ⭐",
                  name.c_str(), "extra[displayName]");
    } else if (name == "channel_action_response_ok_extra") {
        const auto& p = static_cast<const ChannelActionResponsePacket&>(packet);
        CHECK_MSG(p.isSuccess(), name.c_str(), "success");
        CHECK_MSG(p.getAction() == ChannelAction::JOIN, name.c_str(), "action");
        CHECK_MSG(p.getChannelId() == "global", name.c_str(), "channelId");
        CHECK_MSG(p.getErrorCode().empty(), name.c_str(), "errorCode");
        CHECK_MSG(p.getMessage() == "已加入频道", name.c_str(), "message");
        auto it = p.getExtra().find("memberCount");
        CHECK_MSG(it != p.getExtra().end() && it->second == "17", name.c_str(), "extra[memberCount]");
    } else if (name == "config_sync_typical") {
        const auto& p = static_cast<const ConfigSyncPacket&>(packet);
        CHECK_MSG(p.getConfigJson() ==
                  "{\"channels\":[\"global\",\"trade\"],\"motd\":\"今日维护 🛠️\"}",
                  name.c_str(), "configJson");
        CHECK_MSG(p.getTimestamp() == 1755057600000LL, name.c_str(), "timestamp");
    } else if (name == "config_sync_empty_string") {
        const auto& p = static_cast<const ConfigSyncPacket&>(packet);
        CHECK_MSG(p.getConfigJson().empty(), name.c_str(),
                  "configJson stays empty (no \"{}\" normalization)");
        CHECK_MSG(p.getTimestamp() == 0, name.c_str(), "timestamp");
    } else if (name == "keep_alive_max_long") {
        const auto& p = static_cast<const KeepAlivePacket&>(packet);
        CHECK_MSG(p.getTimestamp() == 0x7FFFFFFFFFFFFFFFLL, name.c_str(), "timestamp Long.MAX_VALUE");
    } else if (name == "title_typical") {
        const auto& p = static_cast<const TitlePacket&>(packet);
        CHECK_MSG(p.getChannelId() == "global", name.c_str(), "channelId");
        CHECK_MSG(p.getTitle() == "§6服务器公告", name.c_str(), "title");
        CHECK_MSG(p.getSubtitle() == "Server restart in 5 min ⏰", name.c_str(), "subtitle");
        CHECK_MSG(p.getFadeIn() == 10 && p.getStay() == 70 && p.getFadeOut() == 20,
                  name.c_str(), "fadeIn/stay/fadeOut");
        CHECK_MSG(p.getSenderId() == UUID_A, name.c_str(), "senderId");
    } else if (name == "admin_action_spy_extra") {
        const auto& p = static_cast<const AdminActionPacket&>(packet);
        CHECK_MSG(p.getAction() == AdminAction::SPY_START, name.c_str(), "action");
        CHECK_MSG(p.getPlayerId() == UUID_B, name.c_str(), "playerId");
        CHECK_MSG(p.getPasswordHash().empty(), name.c_str(), "passwordHash");
        CHECK_MSG(p.getTarget() == "vip-频道", name.c_str(), "target");
    } else if (name == "admin_action_response_fail") {
        const auto& p = static_cast<const AdminActionResponsePacket&>(packet);
        CHECK_MSG(p.getAction() == AdminAction::RELOAD, name.c_str(), "action");
        CHECK_MSG(!p.isSuccess(), name.c_str(), "success");
        CHECK_MSG(p.getErrorCode() == "NC-500", name.c_str(), "errorCode");
        CHECK_MSG(p.getMessage() == "配置重载失败", name.c_str(), "message");
    } else if (name == "item_display_typical") {
        const auto& p = static_cast<const ItemDisplayPacket&>(packet);
        CHECK_MSG(p.getSenderId() == UUID_A, name.c_str(), "senderId");
        CHECK_MSG(p.getSenderName() == "Alex", name.c_str(), "senderName");
        CHECK_MSG(p.getChannelId() == "global", name.c_str(), "channelId");
        CHECK_MSG(p.getItemJson() == "{\"id\":\"minecraft:netherite_sword\",\"count\":1}",
                  name.c_str(), "itemJson");
        CHECK_MSG(p.getTimestamp() == 1755057612345LL, name.c_str(), "timestamp");
    } else if (name == "item_display_boundary") {
        const auto& p = static_cast<const ItemDisplayPacket&>(packet);
        CHECK_MSG(p.getSenderId() == UUID_NIL, name.c_str(), "senderId nil");
        CHECK_MSG(p.getTimestamp() == -1LL, name.c_str(), "timestamp -1 (all 0xFF)");
    } else if (name == "mention_typical") {
        const auto& p = static_cast<const MentionPacket&>(packet);
        CHECK_MSG(p.getMentionerId() == UUID_A, name.c_str(), "mentionerId");
        CHECK_MSG(p.getMentionerName() == "Steve", name.c_str(), "mentionerName");
        CHECK_MSG(p.getMentionedId() == UUID_B, name.c_str(), "mentionedId");
        CHECK_MSG(p.getChannelId() == "global", name.c_str(), "channelId");
        CHECK_MSG(p.getMessagePreview() == "@Alex 快来看 👀", name.c_str(), "messagePreview");
        CHECK_MSG(p.getTimestamp() == 1755057699999LL, name.c_str(), "timestamp");
    } else if (name == "private_message_typical") {
        const auto& p = static_cast<const PrivateMessagePacket&>(packet);
        CHECK_MSG(p.getSenderId() == UUID_A, name.c_str(), "senderId");
        CHECK_MSG(p.getSenderName() == "Steve", name.c_str(), "senderName");
        CHECK_MSG(p.getSenderClientId() == "survival-01", name.c_str(), "senderClientId");
        CHECK_MSG(p.getTargetName() == "Alex", name.c_str(), "targetName");
        CHECK_MSG(p.getTargetId() == UUID_B, name.c_str(), "targetId");
        CHECK_MSG(p.getContent() == "Meet me at spawn", name.c_str(), "content");
        CHECK_MSG(p.getTimestamp() == 1755057712345LL, name.c_str(), "timestamp");
    } else if (name == "private_message_cjk_nil_target") {
        const auto& p = static_cast<const PrivateMessagePacket&>(packet);
        CHECK_MSG(p.getSenderId() == UUID_B, name.c_str(), "senderId");
        CHECK_MSG(p.getSenderName() == "玩家·小明", name.c_str(), "senderName (CJK)");
        CHECK_MSG(p.getSenderClientId() == "生存服-01", name.c_str(), "senderClientId (CJK)");
        CHECK_MSG(p.getTargetName() == "Alex", name.c_str(), "targetName");
        CHECK_MSG(p.getTargetId() == UUID_NIL, name.c_str(), "targetId nil (C->S form)");
        CHECK_MSG(p.getContent() == "晚上一起打末影龙吗？🐉✨", name.c_str(), "content (CJK + emoji)");
        CHECK_MSG(p.getTimestamp() == 1755057799999LL, name.c_str(), "timestamp");
    }
}

// ==================== main ====================

int main() {
    fs::path goldenDir = findGoldenDir();
    if (goldenDir.empty() || !fs::exists(goldenDir)) {
        std::printf("FAIL: golden dir not found (set NOVALINK_REPO_ROOT or run from within the repo)\n");
        return 1;
    }
    std::printf("Golden dir: %s\n", goldenDir.string().c_str());

    // Wire forms that omit optional trailing fields: decode-only.
    const std::set<std::string> legacySamples = {
        "handshake_v1_no_serverversion",
        "chat_message_legacy_no_placeholders",
    };

    std::vector<fs::path> binFiles;
    for (const auto& entry : fs::directory_iterator(goldenDir)) {
        if (entry.path().extension() == ".bin") {
            binFiles.push_back(entry.path());
        }
    }
    std::sort(binFiles.begin(), binFiles.end());

    if (binFiles.empty()) {
        std::printf("FAIL: no .bin samples in %s (run the Java GoldenFileGenerator first)\n",
                    goldenDir.string().c_str());
        return 1;
    }

    int decoded = 0;
    std::set<uint8_t> coveredIds;
    std::vector<std::string> skipped;

    for (const auto& binPath : binFiles) {
        const std::string name = binPath.stem().string();
        std::vector<uint8_t> frame = readFile(binPath);

        try {
            // ---- Parse frame: Length(VarInt) | PacketID | RequestID | Payload ----
            PacketBuffer buf(frame);
            int32_t length = buf.readVarInt();
            CHECK_MSG(static_cast<size_t>(length) == buf.readableBytes(), name.c_str(),
                      "VarInt length prefix == body size");

            uint8_t packetId = buf.readByte();
            UUID requestId = buf.readUUID();

            auto packet = createPacket(packetId);
            if (!packet) {
                skipped.push_back(name);
                std::printf("SKIP: [%s] C++ has no packet class for packetId 0x%02X\n",
                            name.c_str(), packetId);
                continue;
            }
            packet->setRequestId(requestId);
            packet->read(buf);
            CHECK_MSG(buf.readableBytes() == 0, name.c_str(), "payload fully consumed");

            ++decoded;
            coveredIds.insert(packetId);
            checkFields(name, *packet);

            // ---- Re-encode ----
            std::vector<uint8_t> reencoded = encodeFrame(*packet);
            if (legacySamples.count(name) == 0) {
                CHECK_MSG(reencoded == frame, name.c_str(),
                          "re-encoded frame is byte-identical to the golden frame");
            }
        } catch (const std::exception& e) {
            ++gFailed;
            std::printf("FAIL: [%s] exception: %s\n", name.c_str(), e.what());
        }
    }

    // All 13 packet ids registered in Java's NovaProtocol must be covered.
    const uint8_t expectedIds[] = {0x01, 0x02, 0x03, 0x04, 0x05, 0x06,
                                   0x07, 0x09, 0x0B, 0x0C, 0x10, 0x12, 0x14};
    for (uint8_t id : expectedIds) {
        CHECK_MSG(coveredIds.count(id) != 0, "coverage", "packet id covered by golden samples");
    }

    std::printf("\nGolden samples: %zu (.bin), decoded: %d, skipped: %zu\n",
                binFiles.size(), decoded, skipped.size());
    for (const auto& s : skipped) {
        std::printf("  skipped: %s\n", s.c_str());
    }
    std::printf("Checks passed: %d, failed: %d\n", gPassed, gFailed);
    return gFailed == 0 ? 0 : 1;
}
