package com.nova.link.channel;

import net.jqwik.api.*;
import net.jqwik.api.constraints.*;

import java.util.*;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Property-based tests for Private Channel ID Uniqueness.
 * 
 * **Feature: starchat-starlink, Property 9: Private Channel ID Uniqueness**
 * 
 * For any two private channels created, their generated IDs should be different.
 * 
 * **Validates: Requirements 7.2**
 */
public class PrivateChannelIdUniquenessPropertyTest {

    /**
     * **Feature: starchat-starlink, Property 9: Private Channel ID Uniqueness**
     * 
     * For any number of private channels created, all generated IDs should be unique.
     * This tests the core uniqueness guarantee of the ID generation algorithm.
     * 
     * **Validates: Requirements 7.2**
     */
    @Property(tries = 100)
    void allGeneratedPrivateChannelIdsShouldBeUnique(
            @ForAll @IntRange(min = 2, max = 50) int numberOfChannels,
            @ForAll @StringLength(min = 1, max = 20) String clientId
    ) {
        // Filter out empty/whitespace-only client IDs (not valid input)
        Assume.that(clientId != null && !clientId.trim().isEmpty());
        
        // Setup
        ChannelManager channelManager = new ChannelManager();
        PrivateChannelManager privateChannelManager = new PrivateChannelManager(channelManager);
        
        Set<String> generatedIds = new HashSet<>();
        
        // Create multiple private channels
        for (int i = 0; i < numberOfChannels; i++) {
            UUID ownerId = UUID.randomUUID();
            String displayName = "Private Channel " + i;
            
            PrivateChannelManager.PrivateChannelCreationResult result = 
                    privateChannelManager.createPrivateChannel(displayName, clientId, ownerId, null);
            
            String channelId = result.getChannelId();
            
            // PROPERTY: Each generated ID should be unique (not seen before)
            assertThat(generatedIds)
                    .as("Channel ID '%s' should be unique, but was already generated", channelId)
                    .doesNotContain(channelId);
            
            generatedIds.add(channelId);
        }
        
        // PROPERTY: Total unique IDs should equal number of channels created
        assertThat(generatedIds)
                .as("All %d channels should have unique IDs", numberOfChannels)
                .hasSize(numberOfChannels);
    }

    /**
     * Property 9 (continued): IDs generated by generateUniqueId() directly should also be unique.
     * 
     * **Validates: Requirements 7.2**
     */
    @Property(tries = 100)
    void generateUniqueIdProducesDistinctIds(
            @ForAll @IntRange(min = 2, max = 100) int numberOfIds
    ) {
        // Setup
        ChannelManager channelManager = new ChannelManager();
        PrivateChannelManager privateChannelManager = new PrivateChannelManager(channelManager);
        
        Set<String> generatedIds = new HashSet<>();
        
        // Generate multiple IDs
        for (int i = 0; i < numberOfIds; i++) {
            String id = privateChannelManager.generateUniqueId();
            
            // PROPERTY: Each generated ID should be unique
            assertThat(generatedIds)
                    .as("ID '%s' should be unique, but was already generated", id)
                    .doesNotContain(id);
            
            generatedIds.add(id);
            
            // Register the ID with channel manager to simulate real usage
            channelManager.createChannel(ChannelConfig.builder()
                    .id(id)
                    .displayName("Test Channel " + i)
                    .scope(ChannelScope.PRIVATE)
                    .clientId("test-client")
                    .ownerId(UUID.randomUUID())
                    .build());
        }
        
        // PROPERTY: Total unique IDs should equal number requested
        assertThat(generatedIds)
                .as("All %d IDs should be unique", numberOfIds)
                .hasSize(numberOfIds);
    }

    /**
     * Property 9 (continued): IDs should follow the NC-XXXX format.
     * 
     * **Validates: Requirements 7.2**
     */
    @Property(tries = 100)
    void generatedIdsShouldFollowCorrectFormat(
            @ForAll @IntRange(min = 1, max = 20) int numberOfChannels,
            @ForAll @StringLength(min = 1, max = 20) String clientId
    ) {
        // Filter out empty/whitespace-only client IDs (not valid input)
        Assume.that(clientId != null && !clientId.trim().isEmpty());
        
        // Setup
        ChannelManager channelManager = new ChannelManager();
        PrivateChannelManager privateChannelManager = new PrivateChannelManager(channelManager);
        
        // Create multiple private channels
        for (int i = 0; i < numberOfChannels; i++) {
            UUID ownerId = UUID.randomUUID();
            
            PrivateChannelManager.PrivateChannelCreationResult result = 
                    privateChannelManager.createPrivateChannel("Channel " + i, clientId, ownerId, null);
            
            String channelId = result.getChannelId();
            
            // PROPERTY: ID should match NC-XXXX format (NC- prefix + 4 hex characters)
            assertThat(channelId)
                    .as("Channel ID should start with 'NC-' prefix")
                    .startsWith("NC-");
            
            assertThat(channelId)
                    .as("Channel ID should be exactly 7 characters (NC- + 4 hex chars)")
                    .hasSize(7);
            
            String hexPart = channelId.substring(3);
            assertThat(hexPart)
                    .as("The 4-character suffix should be hexadecimal")
                    .matches("[0-9A-F]{4}");
        }
    }

    /**
     * Property 9 (continued): Creating channels across different clients should still produce unique IDs.
     * 
     * **Validates: Requirements 7.2**
     */
    @Property(tries = 100)
    void idsAreUniqueAcrossDifferentClients(
            @ForAll @Size(min = 2, max = 5) List<@StringLength(min = 1, max = 20) String> clientIds,
            @ForAll @IntRange(min = 1, max = 10) int channelsPerClient
    ) {
        // Filter out empty/whitespace-only client IDs (not valid input)
        for (String clientId : clientIds) {
            Assume.that(clientId != null && !clientId.trim().isEmpty());
        }
        
        // Ensure unique client IDs
        Set<String> uniqueClientIds = new HashSet<>(clientIds);
        Assume.that(uniqueClientIds.size() >= 2);
        
        // Setup
        ChannelManager channelManager = new ChannelManager();
        PrivateChannelManager privateChannelManager = new PrivateChannelManager(channelManager);
        
        Set<String> allGeneratedIds = new HashSet<>();
        
        // Create channels for each client
        for (String clientId : uniqueClientIds) {
            for (int i = 0; i < channelsPerClient; i++) {
                UUID ownerId = UUID.randomUUID();
                
                PrivateChannelManager.PrivateChannelCreationResult result = 
                        privateChannelManager.createPrivateChannel(
                                "Channel " + clientId + "-" + i, 
                                clientId, 
                                ownerId, 
                                null);
                
                String channelId = result.getChannelId();
                
                // PROPERTY: Each ID should be globally unique across all clients
                assertThat(allGeneratedIds)
                        .as("Channel ID '%s' should be unique across all clients", channelId)
                        .doesNotContain(channelId);
                
                allGeneratedIds.add(channelId);
            }
        }
        
        // PROPERTY: Total unique IDs should equal total channels created
        int expectedTotal = uniqueClientIds.size() * channelsPerClient;
        assertThat(allGeneratedIds)
                .as("All %d channels across %d clients should have unique IDs", 
                        expectedTotal, uniqueClientIds.size())
                .hasSize(expectedTotal);
    }
}
