"""
NovaChat Protocol Implementation for Python/Endstone.

This package contains the NovaProtocol implementation including:
- VarInt encoding/decoding
- Packet buffer operations
- Packet type definitions
"""

from novachat_endstone.protocol.varint import VarInt
from novachat_endstone.protocol.buffer import PacketBuffer
from novachat_endstone.protocol import protocol_limits
from novachat_endstone.protocol.protocol_limits import (
    MAX_FRAME_LENGTH,
    MAX_CONFIG_SYNC_JSON,
    MAX_CHANNEL_ID,
    MAX_CLIENT_ID,
    MAX_SENDER_NAME,
    MAX_TARGET_NAME,
    MAX_ERROR_CODE,
    MAX_ERROR_MESSAGE,
    MAX_TITLE,
    MAX_SUBTITLE,
    MAX_MESSAGE_PREVIEW,
    MAX_MESSAGE_CONTENT,
    MAX_PASSWORD_HASH,
    MAX_HMAC,
    MAX_NONCE,
    MAX_SERVER_VERSION,
    MAX_CHANNEL_PASSWORD,
    MAX_ITEM_JSON,
    MAX_ACTION_JSON,
    MAX_METADATA_KEY,
    MAX_METADATA_VALUE,
)
from novachat_endstone.protocol.packet import (
    Packet,
    PacketIds,
    ChannelAction,
    AdminAction,
    PlatformType,
    HandshakePacket,
    HandshakeResponsePacket,
    HandshakeInitPacket,
    HandshakeChallengePacket,
    HandshakeAuthenticatePacket,
    ChatMessagePacket,
    ChannelActionPacket,
    ChannelActionResponsePacket,
    ConfigSyncPacket,
    KeepAlivePacket,
    TitleMessagePacket,
    ChannelUpdatePacket,
    AdminActionPacket,
    AdminActionResponsePacket,
    ItemDisplayPacket,
    MentionPacket,
    decode_packet,
)

__all__ = [
    "VarInt",
    "PacketBuffer",
    "protocol_limits",
    "MAX_FRAME_LENGTH",
    "MAX_CONFIG_SYNC_JSON",
    "MAX_CHANNEL_ID",
    "MAX_CLIENT_ID",
    "MAX_SENDER_NAME",
    "MAX_TARGET_NAME",
    "MAX_ERROR_CODE",
    "MAX_ERROR_MESSAGE",
    "MAX_TITLE",
    "MAX_SUBTITLE",
    "MAX_MESSAGE_PREVIEW",
    "MAX_MESSAGE_CONTENT",
    "MAX_PASSWORD_HASH",
    "MAX_HMAC",
    "MAX_NONCE",
    "MAX_SERVER_VERSION",
    "MAX_CHANNEL_PASSWORD",
    "MAX_ITEM_JSON",
    "MAX_ACTION_JSON",
    "MAX_METADATA_KEY",
    "MAX_METADATA_VALUE",
    "Packet",
    "PacketIds",
    "ChannelAction",
    "AdminAction",
    "PlatformType",
    "HandshakePacket",
    "HandshakeResponsePacket",
    "HandshakeInitPacket",
    "HandshakeChallengePacket",
    "HandshakeAuthenticatePacket",
    "ChatMessagePacket",
    "ChannelActionPacket",
    "ChannelActionResponsePacket",
    "ConfigSyncPacket",
    "KeepAlivePacket",
    "TitleMessagePacket",
    "ChannelUpdatePacket",
    "AdminActionPacket",
    "AdminActionResponsePacket",
    "ItemDisplayPacket",
    "MentionPacket",
    "decode_packet",
]
