<?php

declare(strict_types=1);

namespace NovaChat\Tests\Protocol;

use NovaChat\Protocol\AdminActionPacket;
use NovaChat\Protocol\AdminActionResponsePacket;
use NovaChat\Protocol\ChannelActionPacket;
use NovaChat\Protocol\ChannelActionResponsePacket;
use NovaChat\Protocol\ChatMessagePacket;
use NovaChat\Protocol\ConfigSyncPacket;
use NovaChat\Protocol\HandshakePacket;
use NovaChat\Protocol\HandshakeResponsePacket;
use NovaChat\Protocol\ItemDisplayPacket;
use NovaChat\Protocol\KeepAlivePacket;
use NovaChat\Protocol\MentionPacket;
use NovaChat\Protocol\Packet;
use NovaChat\Protocol\PacketBuffer;
use NovaChat\Protocol\PrivateMessagePacket;
use NovaChat\Protocol\TitleMessagePacket;
use PHPUnit\Framework\TestCase;

/**
 * Cross-language golden byte verification (PHP side).
 *
 * The golden frames under <repo>/test/protocol-golden are generated by the
 * authoritative Java implementation (NovaChat/common, GoldenFileGenerator).
 * For every sample this test:
 *   1. decodes the .bin frame with the PMMP protocol classes,
 *   2. asserts every decoded field matches the .json descriptor,
 *   3. re-encodes and asserts byte-for-byte equality with the .bin
 *      (skipped for legacyWire samples and PHP knownDrift samples).
 *
 * Historical PHP drift, now fixed (regression-pinned in
 * testFixedDriftIsByteExact):
 *   - ChatMessagePacket used to drop the placeholders map (decode discarded,
 *     encode always wrote varint 0); it now round-trips the map.
 *   - ConfigSyncPacket::encode used to normalize an empty configJson string
 *     to "{}"; like Java it now preserves the empty string.
 */
final class GoldenBytesTest extends TestCase {

    /** @var array<string> collected names of samples PHP cannot decode */
    private static array $skippedSamples = [];

    private static function repoRoot(): string {
        $dir = __DIR__;
        for ($i = 0; $i < 12; $i++) {
            if (file_exists($dir . '/settings.gradle') || file_exists($dir . '/.git')) {
                return $dir;
            }
            $parent = dirname($dir);
            if ($parent === $dir) {
                break;
            }
            $dir = $parent;
        }
        self::fail('Could not locate repository root (settings.gradle/.git) above ' . __DIR__);
    }

    private static function goldenDir(): string {
        return self::repoRoot() . '/test/protocol-golden';
    }

    /**
     * @return array<string, array{0: array<string, mixed>}>
     */
    public static function sampleProvider(): array {
        $manifestPath = self::goldenDir() . '/manifest.json';
        if (!file_exists($manifestPath)) {
            self::fail("Golden manifest not found: $manifestPath (run the Java GoldenFileGenerator first)");
        }
        $manifest = json_decode((string) file_get_contents($manifestPath), true, 512, JSON_THROW_ON_ERROR);

        $cases = [];
        foreach ($manifest['samples'] as $entry) {
            $name = $entry['name'];
            $json = json_decode(
                (string) file_get_contents(self::goldenDir() . '/' . $name . '.json'),
                true, 512, JSON_THROW_ON_ERROR
            );
            $cases[$name] = [$json];
        }
        return $cases;
    }

    /**
     * Samples whose PHP re-encode used to drift from the golden bytes; the
     * drift is fixed and must never come back.
     *
     * @return array<string, array{0: array<string, mixed>}>
     */
    public static function fixedDriftProvider(): array {
        return array_intersect_key(
            self::sampleProvider(),
            array_flip(['chat_message_full', 'config_sync_empty_string'])
        );
    }

    /**
     * @dataProvider sampleProvider
     * @param array<string, mixed> $json
     */
    public function testGoldenSample(array $json): void {
        $name = $json['name'];
        $frame = (string) file_get_contents(self::goldenDir() . '/' . $name . '.bin');

        // ---- Parse frame: Length(VarInt) | PacketID | RequestID | Payload ----
        $buffer = new PacketBuffer($frame);
        $length = $buffer->readVarInt();
        self::assertSame($buffer->remaining(), $length, "$name: VarInt length prefix == body size");
        $body = $buffer->readBytes($length);

        $packet = Packet::fromBytes($body);
        if ($packet === null) {
            self::$skippedSamples[] = sprintf('%s (packetId 0x%02X)', $name, $json['packetId']);
            self::markTestSkipped(sprintf(
                'PHP has no packet class for packetId 0x%02X (sample %s)', $json['packetId'], $name
            ));
        }

        self::assertSame($json['packetId'], $packet->getId(), "$name: packet id");
        self::assertSame($json['requestId'], $packet->getRequestId(), "$name: request id");
        $this->assertFields($name, $packet, $json['fields']);

        // ---- Re-encode ----
        if ($json['reencodeExact'] !== true || isset($json['knownDrift']['php'])) {
            return; // legacy wire form or documented PHP drift: decode-only.
        }
        $reencoded = $packet->serialize();
        self::assertSame(
            bin2hex($frame),
            bin2hex($reencoded),
            "$name: re-encoded frame is byte-identical to the golden frame"
        );
    }

    /**
     * Regression pin for the fixed PHP drift (ChatMessage placeholders were
     * dropped; ConfigSync normalized an empty configJson to "{}"): these
     * samples must now re-encode byte-identical to the golden frame.
     *
     * @dataProvider fixedDriftProvider
     * @param array<string, mixed> $json
     */
    public function testFixedDriftIsByteExact(array $json): void {
        $name = $json['name'];
        $frame = (string) file_get_contents(self::goldenDir() . '/' . $name . '.bin');

        $buffer = new PacketBuffer($frame);
        $length = $buffer->readVarInt();
        $body = $buffer->readBytes($length);
        $packet = Packet::fromBytes($body);
        self::assertNotNull($packet, "$name: decodable");

        self::assertSame(
            bin2hex($frame),
            bin2hex($packet->serialize()),
            "$name: fixed drift must stay fixed (re-encode is byte-identical)"
        );
    }

    /**
     * @param array<string, mixed> $f
     */
    private function assertFields(string $name, Packet $packet, array $f): void {
        if ($packet instanceof HandshakePacket) {
            self::assertSame($f['protocolVersion'], $packet->protocolVersion, "$name: protocolVersion");
            self::assertSame($f['clientId'], $packet->clientId, "$name: clientId");
            self::assertSame($f['passwordHash'], $packet->passwordHash, "$name: passwordHash");
            self::assertSame($f['platform'], $packet->platform, "$name: platform");
            self::assertSame($f['serverVersion'], $packet->serverVersion, "$name: serverVersion");
        } elseif ($packet instanceof HandshakeResponsePacket) {
            self::assertSame($f['success'], $packet->success, "$name: success");
            self::assertSame($f['errorCode'], $packet->errorCode, "$name: errorCode");
            self::assertSame($f['message'], $packet->message, "$name: message");
        } elseif ($packet instanceof ChatMessagePacket) {
            self::assertSame($f['senderId'], $packet->senderId, "$name: senderId");
            self::assertSame($f['senderName'], $packet->senderName, "$name: senderName");
            self::assertSame($f['clientId'], $packet->clientId, "$name: clientId");
            self::assertSame($f['channelId'], $packet->channelId, "$name: channelId");
            self::assertSame($f['content'], $packet->content, "$name: content");
            self::assertSame($f['placeholders'], $packet->placeholders, "$name: placeholders");
        } elseif ($packet instanceof ChannelActionPacket) {
            self::assertSame($f['action'], $packet->action, "$name: action");
            self::assertSame($f['channelId'], $packet->channelId, "$name: channelId");
            self::assertSame($f['password'], $packet->password, "$name: password");
            self::assertSame($f['extra'], $packet->extra, "$name: extra");
        } elseif ($packet instanceof ChannelActionResponsePacket) {
            self::assertSame($f['success'], $packet->success, "$name: success");
            self::assertSame($f['action'], $packet->action, "$name: action");
            self::assertSame($f['channelId'], $packet->channelId, "$name: channelId");
            self::assertSame($f['errorCode'], $packet->errorCode, "$name: errorCode");
            self::assertSame($f['message'], $packet->message, "$name: message");
            self::assertSame($f['extra'], $packet->extra, "$name: extra");
        } elseif ($packet instanceof ConfigSyncPacket) {
            self::assertSame($f['configJson'], $packet->configJson, "$name: configJson");
            self::assertSame($f['timestamp'], $packet->timestamp, "$name: timestamp");
        } elseif ($packet instanceof KeepAlivePacket) {
            self::assertSame($f['timestamp'], $packet->timestamp, "$name: timestamp");
        } elseif ($packet instanceof TitleMessagePacket) {
            self::assertSame($f['channelId'], $packet->channelId, "$name: channelId");
            self::assertSame($f['title'], $packet->title, "$name: title");
            self::assertSame($f['subtitle'], $packet->subtitle, "$name: subtitle");
            self::assertSame($f['fadeIn'], $packet->fadeIn, "$name: fadeIn");
            self::assertSame($f['stay'], $packet->stay, "$name: stay");
            self::assertSame($f['fadeOut'], $packet->fadeOut, "$name: fadeOut");
            self::assertSame($f['senderId'], $packet->senderId, "$name: senderId");
        } elseif ($packet instanceof AdminActionPacket) {
            self::assertSame($f['action'], $packet->action, "$name: action");
            self::assertSame($f['playerId'], $packet->playerId, "$name: playerId");
            self::assertSame($f['passwordHash'], $packet->passwordHash, "$name: passwordHash");
            self::assertSame($f['target'], $packet->target, "$name: target");
            self::assertSame($f['extra'], $packet->extra, "$name: extra");
        } elseif ($packet instanceof AdminActionResponsePacket) {
            self::assertSame($f['action'], $packet->action, "$name: action");
            self::assertSame($f['success'], $packet->success, "$name: success");
            self::assertSame($f['errorCode'], $packet->errorCode, "$name: errorCode");
            self::assertSame($f['message'], $packet->message, "$name: message");
        } elseif ($packet instanceof ItemDisplayPacket) {
            self::assertSame($f['senderId'], $packet->senderId, "$name: senderId");
            self::assertSame($f['senderName'], $packet->senderName, "$name: senderName");
            self::assertSame($f['channelId'], $packet->channelId, "$name: channelId");
            self::assertSame($f['itemJson'], $packet->itemJson, "$name: itemJson");
            self::assertSame($f['timestamp'], $packet->timestamp, "$name: timestamp");
        } elseif ($packet instanceof MentionPacket) {
            self::assertSame($f['mentionerId'], $packet->mentionerId, "$name: mentionerId");
            self::assertSame($f['mentionerName'], $packet->mentionerName, "$name: mentionerName");
            self::assertSame($f['mentionedId'], $packet->mentionedId, "$name: mentionedId");
            self::assertSame($f['channelId'], $packet->channelId, "$name: channelId");
            self::assertSame($f['messagePreview'], $packet->messagePreview, "$name: messagePreview");
            self::assertSame($f['timestamp'], $packet->timestamp, "$name: timestamp");
        } elseif ($packet instanceof PrivateMessagePacket) {
            self::assertSame($f['senderId'], $packet->senderId, "$name: senderId");
            self::assertSame($f['senderName'], $packet->senderName, "$name: senderName");
            self::assertSame($f['senderClientId'], $packet->senderClientId, "$name: senderClientId");
            self::assertSame($f['targetName'], $packet->targetName, "$name: targetName");
            self::assertSame($f['targetId'], $packet->targetId, "$name: targetId");
            self::assertSame($f['content'], $packet->content, "$name: content");
            self::assertSame($f['timestamp'], $packet->timestamp, "$name: timestamp");
        } else {
            self::fail("$name: unhandled packet class " . get_class($packet));
        }
    }
}
